language: go

go_import_path: go.starlark.net

go:
    - "1.12.x"
    - "1.13.x"
    - "1.14.x"
    - "master"

env:
    - "GO111MODULE=on"

script:
    - "go test -mod=readonly ./..."
    - "cp go.mod go.mod.orig"
    - "cp go.sum go.sum.orig"
    - "go mod tidy"
    - "diff go.mod.orig go.mod"
    - "diff go.sum.orig go.sum"
